name: techno_world
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
    #  ------------------------------firabase----------------------
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_analytics: ^10.4.4
  firebase_storage: ^11.2.5
    #  ------------------------------provider----------------------
  provider: ^6.0.5
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.4
    #  ------------------------------helper package----------------------
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  zoom_tap_animation: ^1.1.0
  fluttertoast: ^8.2.2
  image_picker: ^1.0.1
  shimmer: ^3.0.0
  like_button: ^2.0.5
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/


  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/dmSans/DMSans-Regular.ttf
        - asset: assets/fonts/dmSans/DMSans-BlackItalic.ttf
        - asset: assets/fonts/dmSans/DMSans-Black.ttf
        - asset: assets/fonts/dmSans/DMSans-Bold.ttf
        - asset: assets/fonts/dmSans/DMSans-BoldItalic.ttf
        - asset: assets/fonts/dmSans/DMSans-ExtraBold.ttf
        - asset: assets/fonts/dmSans/DMSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/dmSans/DMSans-ExtraLight.ttf
        - asset: assets/fonts/dmSans/DMSans-ExtraLightItalic.ttf
        - asset: assets/fonts/dmSans/DMSans-Italic.ttf
        - asset: assets/fonts/dmSans/DMSans-Light.ttf
        - asset: assets/fonts/dmSans/DMSans-LightItalic.ttf
        - asset: assets/fonts/dmSans/DMSans-Medium.ttf
        - asset: assets/fonts/dmSans/DMSans-MediumItalic.ttf
        - asset: assets/fonts/dmSans/DMSans-SemiBold.ttf
        - asset: assets/fonts/dmSans/DMSans-SemiBold.ttf
        - asset: assets/fonts/dmSans/DMSans-Thin.ttf
        - asset: assets/fonts/dmSans/DMSans-ThinItalic.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/montserrat/Montserrat-ThinItalic.ttf
